# Generated by Django 3.1.5 on 2021-02-21 12:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326, verbose_name='Координаты')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='lost_and_found', verbose_name='Изображение')),
                ('contacts', models.CharField(default='', max_length=200, verbose_name='Контакты')),
                ('description', models.TextField(default='', null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('lost', 'lost'), ('found', 'found')], default='', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('radius', models.FloatField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
