# Generated by Django 3.1.5 on 2021-02-25 10:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326, unique=True, verbose_name='Координаты')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='lost_and_found', verbose_name='Изображение')),
                ('image_url', models.URLField(null=True)),
                ('contacts', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Контакты')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('lost', 'lost'), ('found', 'found')], default='', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('radius', models.FloatField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found', to='world.image')),
                ('lost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost', to='world.image')),
            ],
        ),
    ]
