# Generated by Django 3.1.5 on 2021-02-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_lostfound_seen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lostfound',
            unique_together={('lost', 'found')},
        ),
    ]
