# Generated by Django 3.1.5 on 2021-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20210217_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
    ]
